packages:
  - example/*
  - packages/*

allowBuilds:
  '@prisma/engines': true
  '@swc/core': true
  better-sqlite3: true
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true
  workerd: true

catalog:
  vite: https://pkg.pr.new/voidzero-dev/vite-plus/@voidzero-dev/vite-plus-core@1633
  vite-plus: https://pkg.pr.new/voidzero-dev/vite-plus@1633
  vitest: https://pkg.pr.new/voidzero-dev/vite-plus/@voidzero-dev/vite-plus-test@1633

blockExoticSubdeps: false
minimumReleaseAge: 4320
minimumReleaseAgeExclude:
  - vite-plus
  - '@voidzero-dev/*'
  - '@typescript/native-preview'
  - '@typescript/native-preview-*'
  - '@void/*'
  - '@oxc-project/types'
  - baseline-browser-mapping
  - caniuse-lite
  - '@cloudflare/workers-types'
  - tsx
  - hono

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - better-sqlite3
  - esbuild
  - msgpackr-extract
  - prisma
  - sharp
  - unrs-resolver
  - workerd

overrides:
  vite: 'catalog:'
  vitest: 'catalog:'

peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
