packages:
  - example/*
  - packages/*

minimumReleaseAge: 60
minimumReleaseAgeExclude:
  - '@voidzero-dev/*'
  - vite-plus
  - '@vitest/*'
  - vite
  - vitest
  - '@oxc-project/*'
  - '@oxlint/*'
  - oxlint
  - oxfmt
  - oxlint-tsgolint
blockExoticSubdeps: false

allowBuilds:
  '@prisma/engines': true
  '@swc/core': true
  better-sqlite3: true
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true
  workerd: true

catalog:
  vite: 'https://pkg.pr.new/voidzero-dev/vite-plus/@voidzero-dev/vite-plus-core@1856'
  vite-plus: 'https://pkg.pr.new/voidzero-dev/vite-plus@1856'
  vitest: '4.1.9'

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - better-sqlite3
  - esbuild
  - msgpackr-extract
  - prisma
  - sharp
  - unrs-resolver
  - workerd

overrides:
  kysely: 0.28.17
  vite: 'catalog:'
  vitest: 'catalog:'

peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
