export function createFateClient(..._args: Array<never>): never {
  void _args;
  throw new Error(
    `@nkzw/fate/client is generated by the fate Vite plugin. Add fate({ module: '...' }) to your Vite config.`,
  );
}

// eslint-disable-next-line @typescript-eslint/no-empty-object-type
export interface ClientMutations {}
// eslint-disable-next-line @typescript-eslint/no-empty-object-type
export interface ClientRoots {}
